pyproject.toml: Fix `project.license`
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']
---

See also: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license