cmd(git) Update doctest for latest git behavior
========================== FAILURES ===========================
_____________ [doctest] libvcs.cmd.git.Git.config _____________
1635 edit : Optional[bool]
1636 no_includes : Optional[bool]
1637 includes : Optional[bool]
1638 add : Optional[bool]
1639
1640 Examples
1641 --------
1642 >>> git = Git(path=example_git_repo.path)
1643
1644 >>> git.config()
Expected:
    'error: no action specified'
Got:
    'usage: git config [<options>]Config file location--[no-]global         use global config file--[no-]system         use system config file--[no-]local          use repository config file--[no-]worktree       use per-worktree config file-f, --[no-]file <file>use given config file--[no-]blob <blob-id> read config from given blob objectAction--[no-]get            get value: name [value-pattern]--[no-]get-all        get all values: key [value-pattern]--[no-]get-regexp     get values for regexp: name-regex [value-pattern]--[no-]get-urlmatch   get value specific for the URL: section[.var] URL--[no-]replace-all    replace all matching variables: name value [value-pattern]--[no-]add            add a new variable: name value--[no-]unset          remove a variable: name [value-pattern]--[no-]unset-all      remove all matches: name [value-pattern]--[no-]rename-section rename section: old-name new-name--[no-]remove-section remove a section: name-l, --[no-]list       list all--[no-]fixed-value    use string equality when comparing values to \'value-pattern\'-e, --[no-]edit       open an editor--[no-]get-color      find the color configured: slot [default]--[no-]get-colorbool  find the color setting: slot [stdout-is-tty]Type-t, --[no-]type <type>value is given this type--bool                value is "true" or "false"--int                 value is decimal number--bool-or-int         value is --bool or --int--bool-or-str         value is --bool or string--path                value is a path (file or directory name)--expiry-date         value is an expiry dateOther-z, --[no-]null       terminate values with NUL byte--[no-]name-only      show variable names only--[no-]includes       respect include directives on lookup--[no-]show-origin    show origin of config (file, standard input, blob, command line)--[no-]show-scope     show scope of config (worktree, local, global, system, command)--[no-]default <value>with --get, use default value when missing entry'

/home/t/work/python/libvcs/src/libvcs/cmd/git.py:1644: DocTestFailure
=================== short test summary info ===================
FAILED src/libvcs/cmd/git.py::libvcs.cmd.git.Git.config
=============== 1 failed, 290 passed in 14.33s ================